const ADD_TODO = 'ADD_TODO'
const EDIT_TODO = 'EDIT_TODO'
const DELETE_TODO = 'DELETE_TODO'
const ALL_TODOS = 'ALL_TODOS'
const CHANGE_STATUS = 'CHANGE_STATUS'


export { ADD_TODO, EDIT_TODO, DELETE_TODO, ALL_TODOS, CHANGE_STATUS }
