const ADD_TODO = 'ADD_TODO'
const EDIT_TODO = 'EDIT_TODO'
const DELETE_TODO = 'DELETE_TODO'
const ALL_TODOS = 'ALL_TODOS'
const CHANGE_STATUS = 'CHANGE_STATUS'

const ADD_TODO_SAGA = 'ADD_TODO_SAGA'
const EDIT_TODO_SAGA = 'EDIT_TODO_SAGA'
const DELETE_TODO_SAGA = 'DELETE_TODO_SAGA'
const ALL_TODOS_SAGA = 'ALL_TODOS_SAGA'
const CHANGE_STATUS_SAGA = 'CHANGE_STATUS_SAGA'


export { 
  ADD_TODO, 
  EDIT_TODO, 
  DELETE_TODO, 
  ALL_TODOS, 
  CHANGE_STATUS, 
  ADD_TODO_SAGA,
  EDIT_TODO_SAGA,
  DELETE_TODO_SAGA,
  ALL_TODOS_SAGA,
  CHANGE_STATUS_SAGA
}
